name: bot_tg
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  http: ^1.4.0
  sqlite3: ^2.7.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
